// Generated by CoffeeScript 1.7.1
(function() {
  var PNG, fs;

  fs = require('fs');

  PNG = require('pngjs').PNG;

  module.exports.convert = function(from, to, cb) {
    var bf, i, png, stream, tmp, tmpBuff, x, y, _ref;
    bf = fs.readFileSync(from);
    i = 0;
    if (bf[i] !== 0x50 || bf[++i] !== 0x36) {
      return cb(true);
    }
    i++;
    tmp = '';
    while (bf[++i] !== 0x0A) {
      tmp += String.fromCharCode(bf[i]);
    }
    _ref = tmp.split(' '), x = _ref[0], y = _ref[1];
    x = Number(x);
    y = Number(y);
    tmp = '';
    while (bf[++i] !== 0x0A) {
      tmp += String.fromCharCode(bf[i]);
    }
    if (255 !== Number(tmp)) {
      return cb(true);
    }
    bf = bf.slice(i);
    tmpBuff = new Buffer(x * y * 4);
    tmpBuff.fill(0xff);
    i = 0;
    while (i < x * y) {
      bf.copy(tmpBuff, i * 4, i * 3, i * 3 + 3);
      i++;
    }
    png = new PNG({
      width: x,
      height: y
    });
    tmpBuff.copy(png.data);
    stream = fs.createWriteStream(to);
    png.pack().pipe(stream);
    return stream.on('close', function() {
      return cb(null);
    });
  };

}).call(this);
